### ISSUE TITLE
Java  version not compatible with the Android Developer studio

### ISSUE THREAD

**Issue by pmukher** [sandz-in/csc510_group_l#11]

**Comment by poojaasher** [comment]
which version of java isnt working?

**Comment by ZealGanatra** [comment]
we have decided on java 8 and android studio version 15

**Comment by pmukher** [comment]
I was using initially 6. Have reinstalled version 7. It should work with 7

**Comment by ZealGanatra** [comment]
Pratik lets all of us stick to java 8. Otherwise we will have compatibility issues.

**Comment by sandz-in** [comment]
Closing the issue. Java 8 has been finalized.
