### ISSUE TITLE
Decide on the android SDK version

### ISSUE THREAD

**Issue by ZealGanatra** [sandz-in/csc510_group_l#3]

**Comment by ZealGanatra** [comment]
Which is your guys phone android version.
We will use the  oldest version.

**Comment by ZealGanatra** [comment]
Android 6.0.1

**Comment by sandz-in** [comment]
I use android 5.1

**Comment by okeashwin** [comment]
I am currently using an Android 4.0.3 which runs API level 15.

**Comment by okeashwin** [comment]
So, shall we finalize on using the Android API level 15 for building our app?

**Comment by sandz-in** [comment]
+1

**Comment by poojaasher** [comment]
+1

**Comment by ZealGanatra** [comment]
+1

**Comment by sandz-in** [comment]
Android API 15 will be used.
