### ISSUE TITLE
Interface with the back-end

### ISSUE THREAD

**Issue by okeashwin** [sandz-in/csc510_group_l#38]
Back end server needs to collect the data/metadata about the incoming expense for the concerned ( signed in ) user.

**Comment by sandz-in** [comment]
@okeashwin : I have committed the changes to send the amount and description to backend. Let me know how to get the meta-data about the kind of action like voice,sms,image.

**Comment by okeashwin** [comment]
Added code to POST the submission method type from the front end app to the back-end. The back end framework will need to accommodate for this change via an additional column in the Expenses DB table.

**Comment by sandz-in** [comment]
Added the support to persist the bill type.
