### ISSUE TITLE
Import common-lang jar into android project configuration

### ISSUE THREAD

**Issue by sandz-in** [sandz-in/csc510_group_l#51]
Need to include common-lang.jar into project configuration

**Comment by sandz-in** [comment]
Fixed.

**Comment by okeashwin** [comment]
Did you have to add this 'compile files('libs/commons-lang3-3.4.jar')' to successfully build it ?

**Comment by sandz-in** [comment]
Yup. The jar reference was missing in the build path.

**Comment by okeashwin** [comment]
Okay. The 'fileTree compile' had done the trick for me. Hence, didnt add the jar explicitly.
